name: Run Tests and Generate Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pytest

    # 4. Run tests with coverage
    - name: Run tests with coverage
      run: |
        coverage run --source=. -m pytest  # Запуск тестов с покрытием
        coverage report -m               # Вывод отчета в консоль
