name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Шаг 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest

      # Шаг 4: Run tests and generate coverage report
      - name: Run tests with coverage
        run: |
          coverage run --source=. -m pytest
          mkdir -p coverage_reports  # Если папка уже существует, она не будет пересоздана
          coverage report -m > coverage_reports/coverage.txt  # Перезаписываем отчет, если он уже существует

      # Шаг 5: Commit and push coverage report to main branch
      - name: Commit and push coverage report to main branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Добавляем все изменения (включая файл .coverage и отчет)
          git add .coverage coverage_reports/coverage.txt  # Добавляем нужные файлы в индекс
          
          # Проверяем, есть ли изменения, и если да, выполняем коммит и пуш
          git diff --cached --quiet || git commit -m "Add or update coverage report"  # Коммитим только если есть изменения
          
          # Пушим изменения в ветку main
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main  # Пушим изменения в ветку main
