name: Run Tests and Generate Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pytest

    # 4. Run tests with coverage
    - name: Run tests and generate coverage report
      run: |
        coverage run --source=. -m pytest  # Запуск тестов с покрытием
        coverage report -m               # Вывод отчета в консоль
        coverage html                    # Генерация HTML отчета
        coverage xml                     # Генерация XML отчета для более подробного анализа

    # 5. Upload coverage report as an artifact
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml   # Загружаем XML отчет как артефакт

    # 6. Show test results in the GitHub Actions logs
    - name: Display test results
      run: |
        tail -n 20 coverage_report.txt  # Выводим последние 20 строк отчета для удобства
