name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Шаг 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest

      # Шаг 4: Run tests and generate coverage report
      - name: Run tests with coverage
        run: |
          coverage run --source=. -m pytest || true  # Запускаем тесты, игнорируя ошибки
          mkdir -p coverage_reports  # Создаем папку, если она не существует
          rm -f coverage_reports/coverage.txt  # Удаляем старый отчет, если он есть
          coverage report -m > coverage_reports/coverage.txt  # Генерируем новый отчет

      # Шаг 5: Verify coverage report exists
      - name: Verify coverage report exists
        run: |
          ls -l coverage_reports  # Показываем содержимое папки
          cat coverage_reports/coverage.txt || echo "coverage.txt not found"  # Показываем содержимое отчета

      # Шаг 6: Add changes to git
      - name: Add changes to git
        run: |
          git status  # Показываем статус, чтобы проверить, что файлы есть
          git add .coverage coverage_reports/coverage.txt  # Добавляем отчет и другие изменения в индекс
          git diff --cached --quiet || git commit -m "Add or update coverage report"  # Коммитим изменения, если есть

      # Шаг 7: Push changes to the repository
      - name: Push changes to the repository
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main  # Пушим изменения в ветку main
